# @package _group_

_name: full_encoder
input_feat_per_channel: -1
input_channels: -1
conv_kernel_sizes: "5,5"
conv_channels: 1024

encoder_embed_dim: 384
encoder_ffn_embed_dim: 1536
encoder_layers: 10
encoder_attention_heads: 4
encoder_normalize_before: true  

dropout: 0.1
attention_dropout: 0.1
activation_dropout: 0.1